### ISSUE TITLE
Frontend visual bug

### ISSUE THREAD

**Issue by danielduong8** [GDSCUTM-CommunityProjects/UBoard#25]
![image](https://user-images.githubusercontent.com/59457434/139881008-673e2d52-bbda-4e04-8263-b6193880c811.png)

**Comment by andy9775** [comment]
Can you describe the bug? Is it that everything is red? Is it that the `LOG IN` button is off the page?

**Comment by danielduong8** [comment]
> Is it that the `LOG IN` button is off the page?

This. As well as the fact that the login TabPanels do not adjust properly when changing the viewport size.
